import type { ReactNode } from 'react'

const features = [
  ['01', 'Remember the little things.', 'Manu keeps the context around, so you can stay in the moment instead of keeping every tab open in your head.'],
  ['02', 'Turn a thought into a plan.', 'From “what should I eat?” to “help me sort this out,” Manu makes the next step feel obvious.'],
  ['03', 'Always one message away.', 'No new system to learn. No extra dashboard. Just a calm, capable assistant inside iMessage.'],
]

function Arrow() { return <span aria-hidden="true" className="transition-transform group-hover:translate-x-1">↗</span> }

function Iphone() {
  return (
    <div className="iphone-shadow relative mx-auto w-[235px] rotate-2 sm:w-[260px]">
      <div className="rounded-[2.8rem] border-[7px] border-[#101010] bg-[#101010] p-1 shadow-2xl">
        <div className="relative min-h-[465px] overflow-hidden rounded-[2.25rem] bg-[#f4f1eb] px-4 pb-4 pt-6 sm:min-h-[510px]">
          <div className="absolute left-1/2 top-2 h-5 w-20 -translate-x-1/2 rounded-full bg-[#101010]" />
          <div className="flex items-center justify-between px-1 text-[10px] font-medium text-black/45"><span>9:41</span><span>● ● ●</span></div>
          <div className="mt-8 text-center"><div className="mx-auto flex h-9 w-9 items-center justify-center rounded-full bg-[#f15a3c] text-sm font-semibold text-white">m</div><p className="mt-2 text-[11px] font-medium">Manu</p><p className="text-[9px] text-black/35">iMessage</p></div>
          <div className="mt-10 space-y-3 text-[11px] leading-4"><div className="ml-auto max-w-[83%] rounded-2xl rounded-br-md bg-[#e6f458] px-3 py-2.5 text-black/75">Can you make Friday easy?</div><div className="max-w-[88%] rounded-2xl rounded-bl-md bg-white px-3 py-2.5 text-black/65 shadow-sm">Absolutely. I’ll find somewhere relaxed and keep the options short.</div><div className="ml-auto max-w-[83%] rounded-2xl rounded-br-md bg-[#e6f458] px-3 py-2.5 text-black/75">You know me.</div></div>
          <div className="absolute bottom-4 left-4 right-4 flex items-center gap-2 rounded-full border border-black/10 bg-white/70 px-3 py-2 text-[10px] text-black/35"><span className="flex-1">iMessage</span><span className="flex h-5 w-5 items-center justify-center rounded-full bg-[#f15a3c] text-white">↑</span></div>
        </div>
      </div>
    </div>
  )
}

function LegalSection({ title, children }: { title: string; children: ReactNode }) {
  return <section className="border-t border-black/10 py-7 first:border-0 first:pt-0"><h2 className="text-lg font-medium tracking-[-.03em]">{title}</h2><div className="mt-3 space-y-3 text-sm leading-7 text-black/55">{children}</div></section>
}

function LegalPage({ kind }: { kind: 'privacy' | 'terms' }) {
  const privacy = kind === 'privacy'
  return <main className="min-h-screen bg-[#f3f0e9] text-[#171716]"><nav className="mx-auto flex max-w-[900px] items-center justify-between px-6 py-7"><a href="/" className="text-[1.65rem] font-semibold tracking-[-.09em]">manu<span className="text-[#f15a3c]">.</span></a><a href="/" className="text-xs text-black/50 transition hover:text-black">Back home</a></nav><article className="mx-auto max-w-[900px] px-6 pb-20 pt-14"><p className="text-[11px] font-semibold uppercase tracking-[.24em] text-black/40">Runic Lab · Manu</p><h1 className="mt-5 max-w-2xl text-4xl font-medium leading-[.98] tracking-[-.07em] sm:text-6xl">{privacy ? 'Privacy, in plain language.' : 'The ground rules for using Manu.'}</h1><p className="mt-5 max-w-xl text-sm leading-7 text-black/55">{privacy ? 'How Runic Lab collects, uses, and protects information when you use Manu.' : 'These terms explain the agreement between you and Runic Lab when you use Manu.'}</p><p className="mt-3 text-xs text-black/35">Effective date: August 20, 2026</p><div className="mt-14 max-w-2xl">{privacy ? <PrivacyContent /> : <TermsContent />}</div></article><footer className="border-t border-black/10 px-6 py-6 text-center text-xs text-black/35"><a href="/privacy" className="hover:text-black">Privacy</a><span className="mx-2">·</span><a href="/terms" className="hover:text-black">Terms</a></footer></main>
}

function PrivacyContent() {
  return <><LegalSection title="What Manu is"><p>Manu is an AI assistant from Runic Lab. You can talk to Manu through connected messaging channels and connect services so Manu can help you with tasks.</p></LegalSection><LegalSection title="Information we collect"><p>We collect the information needed to operate Manu, including your account details, display name, email address, connected channel identities, messages sent to or from Manu, saved memories, and connected integration details.</p><p>When you connect Google services, we receive the permissions and account information you approve through Google OAuth. We store the credentials needed to keep the connection working, encrypted at rest.</p></LegalSection><LegalSection title="How we use information"><p>We use information to authenticate you, keep your channels connected, respond to your messages, run requested integrations, personalize responses, maintain memories you ask Manu to keep, prevent abuse, and improve reliability.</p><p>We do not sell your personal information. We do not use your Gmail or Calendar data for advertising.</p></LegalSection><LegalSection title="Google data"><p>Manu only accesses Google data after you explicitly connect a Google service and approve the requested permissions. Gmail and Calendar access is used to provide the features you request. You can disconnect either service from your Manu dashboard at any time.</p></LegalSection><LegalSection title="Sharing and service providers"><p>We share information with service providers only when needed to operate Manu, such as infrastructure, database, messaging, authentication, AI model, and connected integration providers.</p></LegalSection><LegalSection title="Retention and control"><p>We retain account and message information while your account is active or as needed to provide Manu. You can disconnect integrations, delete saved memories, or ask us to delete your account and associated data.</p></LegalSection><LegalSection title="Security"><p>We use reasonable safeguards, including encrypted storage for integration credentials. No online service can promise absolute security, so please do not send passwords, private keys, or other secrets to Manu.</p></LegalSection><LegalSection title="Contact"><p>Questions or deletion requests can be sent to <a className="underline decoration-[#f15a3c] underline-offset-4" href="mailto:privacy@manu.so">privacy@manu.so</a>.</p></LegalSection></>
}

function TermsContent() {
  return <><LegalSection title="Using Manu"><p>You may use Manu if you can legally enter into this agreement. You are responsible for the messages, instructions, and connected accounts you use with Manu.</p></LegalSection><LegalSection title="AI-generated responses"><p>Manu uses AI models and connected services to respond to you. Responses can be incomplete or incorrect, so review important information before relying on it. Manu is not a substitute for professional legal, medical, financial, or other expert advice.</p></LegalSection><LegalSection title="Connected services"><p>When you connect a service, you authorize Manu to use the permissions you approve. You are responsible for reviewing actions before they are taken, especially actions that send messages, create events, change records, or place orders.</p></LegalSection><LegalSection title="Acceptable use"><p>Do not use Manu to break the law, impersonate another person, abuse connected services, access accounts without permission, transmit malicious code, or interfere with Manu or its providers.</p></LegalSection><LegalSection title="Your content"><p>You keep ownership of the content you send to Manu. You give Runic Lab the limited permission needed to process that content, operate the service, provide requested features, and maintain the security and reliability of Manu.</p></LegalSection><LegalSection title="Availability and changes"><p>Manu is provided while we continue developing the service. Features, integrations, and availability may change. We may update these terms when the service changes.</p></LegalSection><LegalSection title="Contact"><p>Questions about these terms can be sent to <a className="underline decoration-[#f15a3c] underline-offset-4" href="mailto:hello@manu.so">hello@manu.so</a>.</p></LegalSection></>
}

function App() {
  const path = window.location.pathname
  if (path === '/privacy') return <LegalPage kind="privacy" />
  if (path === '/terms') return <LegalPage kind="terms" />

  return (
    <main className="min-h-screen overflow-hidden bg-[#f3f0e9] text-[#171716] selection:bg-[#e6f458]">
      <nav className="relative z-10 mx-auto flex max-w-[1280px] items-center justify-between px-6 py-6 md:px-10 lg:px-14"><a href="/" className="text-[1.65rem] font-semibold tracking-[-.09em]">manu<span className="text-[#f15a3c]">.</span></a><div className="hidden items-center gap-8 text-[13px] text-black/50 md:flex"><a className="transition hover:text-black" href="#why-manu">Why Manu</a><a className="transition hover:text-black" href="#how-it-works">How it works</a></div><a href="mailto:hello@manu.so" className="group flex items-center gap-2 rounded-full border border-black/20 px-4 py-2 text-[13px] font-medium text-[#171716] transition hover:border-[#f15a3c] hover:bg-[#f15a3c] hover:text-white">Get early access <Arrow /></a></nav>

      <section className="relative mx-auto max-w-[1280px] px-6 pb-28 pt-20 text-center md:px-10 lg:pb-36 lg:pt-28"><div className="pointer-events-none absolute left-1/2 top-20 h-[28rem] w-[42rem] -translate-x-1/2 rounded-full bg-[#f15a3c]/10 blur-3xl" /><div className="relative z-10 mx-auto max-w-4xl"><div className="mx-auto mb-7 flex w-fit items-center gap-2 rounded-full border border-black/15 px-4 py-2 text-[11px] font-medium text-black/55"><span className="h-1.5 w-1.5 rounded-full bg-[#f15a3c]" /> Your assistant, for real life</div><h1 className="mx-auto max-w-4xl text-[4.1rem] font-medium leading-[.91] tracking-[-.08em] sm:text-7xl lg:text-[7.2rem]">Make room for <em className="font-serif font-normal text-[#f15a3c]">more.</em></h1><p className="mx-auto mt-7 max-w-lg text-base leading-7 text-black/55 sm:text-lg">Manu helps you think, plan, and get things done — right from the place you already message.</p><div className="mt-9 flex flex-wrap items-center justify-center gap-3"><a href="mailto:hello@manu.so" className="group flex items-center gap-3 rounded-full bg-[#171716] px-6 py-3.5 text-sm font-medium text-white transition hover:bg-[#f15a3c]">Meet Manu <span className="flex h-6 w-6 items-center justify-center rounded-full bg-white/15"><Arrow /></span></a><a href="#how-it-works" className="rounded-full border border-black/20 px-6 py-3.5 text-sm font-medium text-[#171716] transition hover:border-black hover:bg-white">See how it works</a></div></div><div className="relative z-10 mx-auto mt-16 w-fit"><div className="absolute -left-24 top-20 hidden -rotate-6 rounded-xl bg-[#e6f458] px-4 py-3 text-xs font-medium shadow-lg sm:block">Keeps up with you.</div><Iphone /><div className="absolute -right-24 bottom-12 hidden rotate-6 rounded-xl border border-black/10 bg-white px-4 py-3 text-xs font-medium shadow-lg sm:block">Less juggling.<br /><span className="text-black/40">More living.</span></div></div><div className="mt-20 flex items-center justify-between border-t border-black/10 pt-5 text-left text-[10px] font-medium uppercase tracking-[.2em] text-black/35"><span>Scroll to explore</span><span>01 — 03</span></div></section>

      <section id="why-manu" className="border-y border-black/10 bg-white px-6 py-24 md:px-10 lg:px-14 lg:py-32"><div className="mx-auto grid max-w-[1280px] gap-10 lg:grid-cols-[.55fr_1.45fr]"><p className="text-[11px] font-semibold uppercase tracking-[.24em] text-black/40">Why Manu</p><div><h2 className="max-w-4xl text-4xl font-medium leading-[.96] tracking-[-.07em] sm:text-6xl lg:text-7xl">A little more headspace for the things that matter.</h2><p className="mt-8 max-w-xl text-lg leading-8 text-black/50">Life is already full of tabs, reminders, and half-finished thoughts. Manu helps turn all that noise into momentum.</p></div></div></section>

      <section id="how-it-works" className="mx-auto max-w-[1280px] px-6 py-24 md:px-10 lg:px-14 lg:py-36"><div className="grid gap-14 lg:grid-cols-[.55fr_1.45fr]"><div><p className="text-[11px] font-semibold uppercase tracking-[.24em] text-black/40">Built around you</p><p className="mt-8 max-w-xs text-sm leading-6 text-black/45">The best assistant feels less like software and more like someone who knows how you think.</p></div><div className="divide-y divide-black/10">{features.map(([number, title, copy]) => <article key={number} className="grid gap-5 py-8 first:pt-0 sm:grid-cols-[70px_1fr] sm:gap-8"><span className="text-xs font-medium text-[#f15a3c]">{number}</span><div className="grid gap-5 md:grid-cols-[1fr_.8fr] md:gap-10"><h3 className="max-w-md text-3xl font-medium leading-[.98] tracking-[-.055em] sm:text-4xl">{title}</h3><p className="max-w-sm text-sm leading-6 text-black/48">{copy}</p></div></article>)}</div></div></section>

      <section className="px-6 pb-24 md:px-10 lg:px-14 lg:pb-32"><div className="pixel-cta relative mx-auto max-w-[1280px] overflow-hidden rounded-[2rem] px-6 py-20 text-center text-white sm:px-10 lg:py-28"><div className="relative z-10 mx-auto max-w-2xl"><p className="mb-5 text-[11px] font-semibold uppercase tracking-[.24em] text-white/55">Start somewhere</p><h2 className="text-5xl font-medium leading-[.92] tracking-[-.07em] sm:text-7xl">Ready to make a little more room?</h2><p className="mx-auto mt-6 max-w-md text-sm leading-6 text-white/55">Join the early list for Manu. Your future self will thank you.</p><a href="mailto:hello@manu.so" className="mt-8 inline-flex items-center gap-3 rounded-full bg-white px-6 py-3.5 text-sm font-medium text-[#171716] transition hover:bg-[#e6f458]">Get early access <Arrow /></a></div></div></section>

      <footer className="relative h-[330px] overflow-hidden bg-[#171716] px-6 pt-10 text-white md:px-10 lg:px-14"><div className="relative z-10 mx-auto flex max-w-[1280px] items-start justify-between text-sm"><span className="font-medium">manu<span className="text-[#f15a3c]">.</span></span><div className="flex gap-8 text-white/45"><a className="transition hover:text-white" href="mailto:hello@manu.so">Contact</a><a className="transition hover:text-white" href="#why-manu">About</a></div></div><div className="pointer-events-none absolute bottom-[-.13em] left-1/2 -translate-x-1/2 whitespace-nowrap text-[31vw] font-semibold leading-[.7] tracking-[-.07em] text-white/[.065] sm:text-[27vw]">MANU</div><div className="absolute bottom-5 left-6 right-6 z-10 flex justify-between border-t border-white/10 pt-4 text-[11px] text-white/35 md:left-10 md:right-10 lg:left-14 lg:right-14"><span>© {new Date().getFullYear()} Manu</span><span>Made for the moments between messages.</span></div></footer>
    </main>
  )
}

export default App
